### ISSUE TITLE
Crash when selecting components to load

### ISSUE THREAD

**Issue by erry2907** [ahmsville/Pick-N-Place_Wheel#1]
Hello Ahmed,

I bought your pick-n-place board a while a go, and then didn't find the time to use it.
But now the time came and i want to use it.
But during setting up the applications seems to crash.

This happens when i select a component from the dropdown to fill the slots.

Looking forward to your reply.
Best regards,
Erwin
[PST-USBhub.txt](https://github.com/ahmsville/Pick-N-Place_Wheel/files/10712227/PST-USBhub.txt)
![PST-USBhub_BOT](https://user-images.githubusercontent.com/4432085/218229045-6d068dde-037d-4fef-be7a-307dc5c45c2a.png)
![PST-USBhub_TOP](https://user-images.githubusercontent.com/4432085/218229046-ba6f93e0-e7bf-47fd-becd-c49aac30d67f.png)
[PST-USBhub-PNP_comma.csv](https://github.com/ahmsville/Pick-N-Place_Wheel/files/10712228/PST-USBhub-PNP_comma.csv)

**Comment by ahmsville** [comment]
Hi Erwin.

I looked at your files, everything is in order except for the csv, the x center and y center values are in the wrong format, you can see this when you open the file in a text editor.
Your csv columns should be separated by commas and decimal values should use dot separators, you can download a sample project [Here](https://github.com/ahmsville/Pick-N-Place_Wheel/blob/master/Assembly%20and%20Setup%20Instructions/Example%20Wheel%20Project%20Folder-Files.zip)  to see a csv sample.

If your are using altium, make sure the seperator is set to dot, not comma as this refers to the decimal seperator not the column seperator.

**Comment by erry2907** [comment]
Hello Ahmed,

Thank you for your quick response.
It turned out that the Settings for my CSV export in windows where incorrect.
Now all is working.

I use Kicad, this a bit strange on the export.
All components on the bottom side of the board have a negative X pos value.
But with the ABS() feature in Excel this is easily changed.

I was wondering what the big arrow buttons are used for?
Because the cause the app also to crash.

Loooking forward to your reply.

**Comment by ahmsville** [comment]
Hi Erwin,

Glad to hear it's working, the buttons are used to move between projects in the same folder, so the crash is probably caused by invalid project folders/files. look out for v2 of the app releasing soon with a lot of bug fixes, and new features.
